# Generated by Django 5.0 on 2025-03-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='region',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sms',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
